version: 2
updates:
  - package-ecosystem: composer
    directory: /
    target-branch: '8.1'
    schedule:
      interval: weekly
    groups:
      symfony:
        patterns:
          - 'symfony/*'

  - package-ecosystem: github-actions
    directory: /
    target-branch: '8.1'
    schedule:
      interval: weekly
